apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: LoadBalancer  # Rend le service accessible via un port du nœud
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080  # Port interne du service
      targetPort: 8080  # Port sur lequel le pod écoute